/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iWallnutSol from "./iWallnut.sol";
export type { iWallnutSol };
import type * as wFactorySol from "./wFactory.sol";
export type { wFactorySol };
import type * as wallnutSol from "./wallnut.sol";
export type { wallnutSol };
