/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWallnut,
  IWallnutInterface,
} from "../../../contracts/iWallnut.sol/IWallnut";

const _abi = [
  {
    inputs: [],
    name: "isActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWallnut__factory {
  static readonly abi = _abi;
  static createInterface(): IWallnutInterface {
    return new utils.Interface(_abi) as IWallnutInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWallnut {
    return new Contract(address, _abi, signerOrProvider) as IWallnut;
  }
}
