/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPaymasterFlow,
  IPaymasterFlowInterface,
} from "../../../../../../@matterlabs/zksync-contracts/l2/system-contracts/interfaces/IPaymasterFlow";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minAllowance",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_innerInput",
        type: "bytes",
      },
    ],
    name: "approvalBased",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "general",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPaymasterFlow__factory {
  static readonly abi = _abi;
  static createInterface(): IPaymasterFlowInterface {
    return new utils.Interface(_abi) as IPaymasterFlowInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPaymasterFlow {
    return new Contract(address, _abi, signerOrProvider) as IPaymasterFlow;
  }
}
